### Test
GET http://localhost:5000

// USERS
### Register user
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "janedoe@gmail.com",
    "password": "janedoe"
}

### Get users
GET http://localhost:5000/api/users

### Login user
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "abdoerrahiem@gmail.com",
    "password": "abdoerrahiem"
}

### Get current user
GET http://localhost:5000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhYmRvZXJyYWhpZW1AZ21haWwuY29tIiwiaWF0IjoxNjEzMTE3MTk2LCJleHAiOjE2MTMyMDM1OTZ9.UKPMo3b3Z2zShdWJWww483dMxi3lzC8n8XEtZoMxS1w



// POST
### Create post
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlhdCI6MTYxMjc3NjkzOCwiZXhwIjoxNjEyODYzMzM4fQ.btYCKWBRHS9NSkFXO3NwMqNAVkfRjDeiumS1FW5bI1w

{
    "text": "This is my post 3"
}

### Get posts
GET http://localhost:5000/api/posts

### Get post
GET http://localhost:5000/api/posts/4

### Delete post
DELETE http://localhost:5000/api/posts/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhYmRvZXJyYWhpZW1AZ21haWwuY29tIiwiaWF0IjoxNjEyNDUzNzkzLCJleHAiOjE2MTI1NDAxOTN9.ot4lJ2ODUfuuWTlBgw1uYXjabcxIZqYqs9Cct7LeGFM

### Add like to post
POST http://localhost:5000/api/posts/1/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlhdCI6MTYxMjc3NjkzOCwiZXhwIjoxNjEyODYzMzM4fQ.btYCKWBRHS9NSkFXO3NwMqNAVkfRjDeiumS1FW5bI1w

### Unlike post
DELETE http://localhost:5000/api/posts/3/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlhdCI6MTYxMjQ1NTUxMiwiZXhwIjoxNjEyNTQxOTEyfQ.VSJ4ClcFaOZWn8InYazoeiYvx3qGV6KfDa9w9MwrpyI

### Get likes by post
GET http://localhost:5000/api/posts/3/like


### Add comment to post
POST http://localhost:5000/api/posts/1/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlhdCI6MTYxMjc3NjkzOCwiZXhwIjoxNjEyODYzMzM4fQ.btYCKWBRHS9NSkFXO3NwMqNAVkfRjDeiumS1FW5bI1w

{
    "text": "Great post from me"
}

### Get comments by post
GET http://localhost:5000/api/posts/3/comment

### Delete comment
DELETE http://localhost:5000/api/posts/3/comment?id=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlhdCI6MTYxMjQ1NjU1NSwiZXhwIjoxNjEyNTQyOTU1fQ.1do-LN5OosVZ0ljgSNocNQSO3PYlTux0C3q9ccrI8Uk


// Profiles
### Create / Edit profile
POST http://localhost:5000/api/profiles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlhdCI6MTYxMjc3NjkzOCwiZXhwIjoxNjEyODYzMzM4fQ.btYCKWBRHS9NSkFXO3NwMqNAVkfRjDeiumS1FW5bI1w

{
    "company": "My Company",
    "website": "abdoerrahiem.com",
    "location": "Mempawah, Indonesia",
    "status": "Web Developer",
    "skills": "Web design, web developer",
    "bio": "My bio",
    "githubusername": "abdoerrahiem",
    "youtube": "www.youtube.com/youtube",
    "twitter": "www.twitter.com/twitter",
    "facebook": "www.facebook.com/facebook.com",
    "linkedin": "www.linkedin.com/linkedin",
    "instagram": "www.instagram.com/instagram"
}

### Get current user profile
GET http://localhost:5000/api/profiles/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlhdCI6MTYxMjc3NjkzOCwiZXhwIjoxNjEyODYzMzM4fQ.btYCKWBRHS9NSkFXO3NwMqNAVkfRjDeiumS1FW5bI1w


### Get profiles
GET http://localhost:5000/api/profiles


### Get profile
GET http://localhost:5000/api/profiles/1

### Delete profile
DELETE http://localhost:5000/api/profiles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlhdCI6MTYxMjc3NjkzOCwiZXhwIjoxNjEyODYzMzM4fQ.btYCKWBRHS9NSkFXO3NwMqNAVkfRjDeiumS1FW5bI1w

### Add experience
POST http://localhost:5000/api/profiles/2/experiences
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhYmRvZXJyYWhpZW1AZ21haWwuY29tIiwiaWF0IjoxNjEyNzgwODk1LCJleHAiOjE2MTI4NjcyOTV9.rf8XgLERvi1JE1Bp-T5_FvHFDPDA9I0FOxfZPz80CQA

{
    "title": "Phd",
    "company": "Company 1",
    "location": "Mempawah, Indonesia",
    "from": "1999-12-16",
    "to": "2020-12-16",
    "current": true,
    "description": "description"
}

### Delete experience
DELETE http://localhost:5000/api/profiles/experiences/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhYmRvZXJyYWhpZW1AZ21haWwuY29tIiwiaWF0IjoxNjEyNzgwODk1LCJleHAiOjE2MTI4NjcyOTV9.rf8XgLERvi1JE1Bp-T5_FvHFDPDA9I0FOxfZPz80CQA

### Add education
POST http://localhost:5000/api/profiles/2/educations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhYmRvZXJyYWhpZW1AZ21haWwuY29tIiwiaWF0IjoxNjEyNzgwODk1LCJleHAiOjE2MTI4NjcyOTV9.rf8XgLERvi1JE1Bp-T5_FvHFDPDA9I0FOxfZPz80CQA

{
    "school": "SDN 17",
    "degree": "Sekolah Dasar",
    "fieldofstudy": "pelajaran umum",
    "from": "1999-12-16",
    "to": "2020-12-16",
    "current": true,
    "description": "description"
}

### Delete education
DELETE http://localhost:5000/api/profiles/educations/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhYmRvZXJyYWhpZW1AZ21haWwuY29tIiwiaWF0IjoxNjEyNzgwODk1LCJleHAiOjE2MTI4NjcyOTV9.rf8XgLERvi1JE1Bp-T5_FvHFDPDA9I0FOxfZPz80CQA

### Get users repos
GET http://localhost:5000/api/profiles/github/abdoerrahiem